function T = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  T = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  T = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  T = importfile("C:\Users\eimmone\Documents\Science\SCATES\models\ECMS_paper_validation\fluent\spherical\zone-temperatures-rfile.out", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jan-2025 15:12:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["timestep", "Core", "Duct_core", "Insulation", "Duct_insulation", "time", "Var7"];
opts.SelectedVariableNames = ["timestep", "Core", "Duct_core", "Insulation", "Duct_insulation", "time"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var7", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var7", "EmptyFieldRule", "auto");

% Import the data
T = readtable(filename, opts);

end